// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Agent implements IAgent {
	/**
	 * 
	 */
	private Player player;

	/**
	 * 
	 * @return 
	 */
	public Action makeDecision() {
	}

	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
	}

	/**
	 * 
	 * @param availableActions 
	 * @return 
	 */
	public Action chooseRandomAction(List availableActions) {
	}

	/**
	 * 
	 * @param board 
	 * @param resourceBank 
	 * @return 
	 */
	public void takeTurn(Board board, ResourceBank resourceBank) {
	}
}
