// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Node[] node;
	/**
	 * 
	 */
	private Edge[] edge;
	/**
	 * 
	 */
	private List[] tiles;
	/**
	 * 
	 */
	private List[] nodes;
	/**
	 * 
	 */
	private List[] edges;
	/**
	 * 
	 */
	private Node[] node;
	/**
	 * 
	 */
	private Tile[] tile;
	/**
	 * 
	 */
	private Edge[] edge;
	/**
	 * 
	 */
	public Robber robber;

	/**
	 * 
	 * @param tiles 
	 * @param nodes 
	 * @param edges 
	 */
	public void Board(List tiles, List nodes, List edges) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Tile getTile(int id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Node getNode(int id) {
	}

	/**
	 * 
	 * @param id 
	 * @return 
	 */
	public Edge getEdge(int id) {
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean isValidSettlementPlacement(Node node, Player player) {
	}

	/**
	 * 
	 * @param edge 
	 * @param Player 
	 * @return 
	 */
	public boolean isValidRoadPlacement(Edge edge, Player Player) {
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean isValidCityPlacement(Node node, Player player) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public List getAdjacentNodes(Node node) {
	}

	/**
	 * 
	 * @param node 
	 * @param player 
	 * @return 
	 */
	public boolean hasAdjacentStructures(Node node, Player player) {
	}

	/**
	 * 
	 * @param node 
	 * @return 
	 */
	public List getAdjacentEdges(Node node) {
	}
}
