// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class City extends Structure {
	/**
	 * 
	 * @param owner 
	 */
	public void City(Player owner) {
	}

	/**
	 * 
	 * @return 
	 */
	public int victoryPoints() {
	}
}
