// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class CommandParser {
	/**
	 * 
	 */
	public void parse(input: String):

	Action() {
	}

	/**
	 * 
	 */
	public void isValid(input: String): boolean() {
	}
}
