// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Configuration {
	/**
	 * 
	 */
	private int maxRounds;

	/**
	 * 
	 * @return 
	 * @param filePath 
	 */
	public void loadFromFile(String filePath) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getMaxRounds() {
	}
}
