// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	public Player[] player;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private int round;
	/**
	 * 
	 */
	private int targetVictoryPoints;
	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private boolean isGameOver;
	/**
	 * 
	 */
	public Configuration configuration;
	/**
	 * 
	 */
	public IAgent[] agent;
	/**
	 * 
	 */
	public ResourceBank resourcebank;
	/**
	 * 
	 */
	public GameStateExporter gamestateexporter;

	/**
	 * 
	 * @param board 
	 * @param players 
	 */
	public void Game(Board board, List players) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public void playRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkTermination() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinner() {
	}

	/**
	 * 
	 * @return 
	 */
	public void startGame() {
	}

	/**
	 * 
	 * @return 
	 */
	public void playRound() {
	}

	/**
	 * 
	 * @return 
	 */
	public void printRoundSummary() {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceBank getResourceBank() {
	}
}
