// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class GameStateExporter {
	/**
	 * 
	 */
	public void write(game: Game): void() {
	}

	/**
	 * 
	 */
	public void getFilePath():

	String() {
	}
}
