// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class HumanAgent {
	/**
				 * 
				 */
				private undef scanner:Scanner;

	/**
	 * 
	 */
	public void takeTurn(roundNumber: int, board: Board, resourceBank: ResourceBank): Action, + waitForGo(): void() {
	}

	/**
	 * 
	 */
	public void takeTurn(roundNumber: int, board: Board, resourceBank: ResourceBank):Action() {
	}

	/**
	 * 
	 */
	public void waitForGo(): void() {
	}
}
