// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public interface IAgent {
	/**
				 * 
				 */
				public undef takeTurn(roundNumber: int, board: Board, resourceBank: ResourceBank): Action;
}
