// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	public Structure structure;
	/**
	 * 
	 */
	private int id;

	/**
	 * 
	 * @param id 
	 */
	public void Node(int id) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}
}
