// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private EMap resources;

	/**
	 * 
	 */
	public void ResourceHand() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getBrick() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getLumber() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getWool() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getGrain() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getOre() {
	}

	/**
	 * 
	 * @return 
	 */
	public int totalCards() {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public void add(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean canAfford(EMap cost) {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean spend(EMap cost) {
	}
}
