// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class ResourceBank {
	/**
	 * 
	 */
	private EMap availableResources;

	/**
	 * 
	 */
	public void ResourceBank() {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean hasResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public boolean takeResource(ResourceType type, int amount) {
	}

	/**
	 * 
	 * @param type 
	 * @return 
	 */
	public int getRemainingCount(ResourceType type) {
	}

	/**
	 * 
	 * @param type 
	 * @param amount 
	 * @return 
	 */
	public void returnResource(ResourceType type, int amount) {
	}
}
