// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Edge edge;
	/**
	 * 
	 */
	private Player owner;

	/**
	 * 
	 * @param owner 
	 * @param edge 
	 */
	public void Road(Player owner, Edge edge) {
	}

	/**
	 * 
	 * @return 
	 */
	public Edge getEdge() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}
}
