// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Robber {
	/**
	 * 
	 */
	public Tile location;

	/**
	 * 
	 */
	public void move(tile: Tile): void() {
	}

	/**
	 * 
	 */
	public void getLocation():

	Tile() {
	}
}
