// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Settlement extends Structure {
	/**
	 * 
	 * @param owner 
	 */
	public void Settlement(Player owner) {
	}
}
