// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public abstract class Structure {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node location;

	/**
	 * 
	 * @return 
	 */
	public Player getOwner() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public Node getLocation() {
	}

	/**
	 * 
	 * @param owner 
	 * @param location 
	 */
	public void structure(Player owner, Node location) {
	}
}
