// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int number;

	/**
	 * 
	 * @param id 
	 * @param resourceType 
	 * @param number 
	 */
	public void Tile(catandomainmodel.Tile.int id, ResourceType resourceType, int number) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getId() {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceType getResourceType() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getNumber() {
	}
}
