// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catandomainmodel;

/************************************************************/
/**
 * 
 */
public class TradeOffer {
	/**
	 * 
	 */
	private ResourceHand offeredResources;
	/**
				 * 
				 */
				private ResourceHand requestedResources;

	/**
	 * 
	 */
	public void accept(): void() {
	}

	/**
	 * 
	 */
	public void reject(): void() {
	}
}
